# Generated by Django 4.1.1 on 2022-09-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='date',
            field=models.DateField(default='2020-09-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='organizer_email',
            field=models.EmailField(default='cabeceirasDeBasto@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
